FROM python:3.8.10
WORKDIR /WORK_DOCKER

COPY *.py .          
#захуярюю в попередню папку (ворк) і копіюю всі .РУ
#комент в докері тільки на початку рядку канає

CMD ["sh", "-c", "tail -f /dev/null"]
